extends Node

# 🎮 THE SAFE PLACE - SYSTEM BOOT SEQUENCE
# Simula il caricamento del sistema operativo come nei vecchi PC

@onready var crt_display: ColorRect = $CRTDisplay
@onready var boot_text: RichTextLabel = $BootContainer/BootText

var boot_timer: float = 0.0
var current_step: int = 0

# Sequenza di boot con timing realistico
const BOOT_SEQUENCE = [
	{"delay": 0.5, "text": "[color=#00FF41]THE SAFE PLACE v0.9.7.5 - SYSTEM BOOT SEQUENCE[/color]\n\n[color=#66FF66]Initializing core systems...[/color]"},
		{"delay": 1.0, "text": "[color=#00FF41]THE SAFE PLACE v0.9.7.5 - SYSTEM BOOT SEQUENCE[/color]\n\n[color=#66FF66]Initializing core systems...[/color]\n[color=#FFFF00]Loading BIOS... OK[/color]"},
		{"delay": 0.8, "text": "[color=#00FF41]THE SAFE PLACE v0.9.7.5 - SYSTEM BOOT SEQUENCE[/color]\n\n[color=#66FF66]Initializing core systems...[/color]\n[color=#FFFF00]Loading BIOS... OK[/color]\n[color=#FFFF00]POST (Power-On Self Test)... OK[/color]"},
		{"delay": 1.2, "text": "[color=#00FF41]THE SAFE PLACE v0.9.7.5 - SYSTEM BOOT SEQUENCE[/color]\n\n[color=#66FF66]Initializing core systems...[/color]\n[color=#FFFF00]Loading BIOS... OK[/color]\n[color=#FFFF00]POST (Power-On Self Test)... OK[/color]\n[color=#FFFF00]Detecting hardware...[/color]"},
		{"delay": 0.6, "text": "[color=#00FF41]THE SAFE PLACE v0.9.7.5 - SYSTEM BOOT SEQUENCE[/color]\n\n[color=#66FF66]Initializing core systems...[/color]\n[color=#FFFF00]Loading BIOS... OK[/color]\n[color=#FFFF00]POST (Power-On Self Test)... OK[/color]\n[color=#FFFF00]Detecting hardware...[/color]\n[color=#00FF00]  - CPU: 4.77 MHz 8088 Compatible[/color]\n[color=#00FF00]  - RAM: 640 KB OK[/color]"},
		{"delay": 0.4, "text": "[color=#00FF41]THE SAFE PLACE v0.9.7.5 - SYSTEM BOOT SEQUENCE[/color]\n\n[color=#66FF66]Initializing core systems...[/color]\n[color=#FFFF00]Loading BIOS... OK[/color]\n[color=#FFFF00]POST (Power-On Self Test)... OK[/color]\n[color=#FFFF00]Detecting hardware...[/color]\n[color=#00FF00]  - CPU: 4.77 MHz 8088 Compatible[/color]\n[color=#00FF00]  - RAM: 640 KB OK[/color]"},
		{"delay": 0.5, "text": "[color=#00FF41]THE SAFE PLACE v0.9.7.5 - SYSTEM BOOT SEQUENCE[/color]\n\n[color=#66FF66]Initializing core systems...[/color]\n[color=#FFFF00]Loading BIOS... OK[/color]\n[color=#FFFF00]POST (Power-On Self Test)... OK[/color]\n[color=#FFFF00]Detecting hardware...[/color]\n[color=#00FF00]  - CPU: 4.77 MHz 8088 Compatible[/color]\n[color=#00FF00]  - RAM: 640 KB OK[/color]\n[color=#00FF00]  - CRT Display: Green Phosphor Monitor OK[/color]"},
		{"delay": 1.0, "text": "[color=#00FF41]THE SAFE PLACE v0.9.7.5 - SYSTEM BOOT SEQUENCE[/color]\n\n[color=#66FF66]Initializing core systems...[/color]\n[color=#FFFF00]Loading BIOS... OK[/color]\n[color=#FFFF00]POST (Power-On Self Test)... OK[/color]\n[color=#FFFF00]Detecting hardware...[/color]\n[color=#00FF00]  - CPU: 4.77 MHz 8088 Compatible[/color]\n[color=#00FF00]  - RAM: 640 KB OK[/color]\n[color=#00FF00]  - CRT Display: Green Phosphor Monitor OK[/color]\n[color=#FFFF00]Loading device drivers...[/color]"},
		{"delay": 0.7, "text": "[color=#00FF41]THE SAFE PLACE v0.9.7.5 - SYSTEM BOOT SEQUENCE[/color]\n\n[color=#66FF66]Initializing core systems...[/color]\n[color=#FFFF00]Loading BIOS... OK[/color]\n[color=#FFFF00]POST (Power-On Self Test)... OK[/color]\n[color=#FFFF00]Detecting hardware...[/color]\n[color=#00FF00]  - CPU: 4.77 MHz 8088 Compatible[/color]\n[color=#00FF00]  - RAM: 640 KB OK[/color]\n[color=#00FF00]  - CRT Display: Green Phosphor Monitor OK[/color]\n[color=#FFFF00]Loading device drivers...[/color]\n[color=#00FF00]  - Keyboard driver loaded[/color]"},
		{"delay": 0.5, "text": "[color=#00FF41]THE SAFE PLACE v0.9.7.5 - SYSTEM BOOT SEQUENCE[/color]\n\n[color=#66FF66]Initializing core systems...[/color]\n[color=#FFFF00]Loading BIOS... OK[/color]\n[color=#FFFF00]POST (Power-On Self Test)... OK[/color]\n[color=#FFFF00]Detecting hardware...[/color]\n[color=#00FF00]  - CPU: 4.77 MHz 8088 Compatible[/color]\n[color=#00FF00]  - RAM: 640 KB OK[/color]\n[color=#00FF00]  - CRT Display: Green Phosphor Monitor OK[/color]\n[color=#FFFF00]Loading device drivers...[/color]\n[color=#00FF00]  - Keyboard driver loaded[/color]\n[color=#00FF00]  - Timer driver loaded[/color]"},
		{"delay": 0.6, "text": "[color=#00FF41]THE SAFE PLACE v0.9.7.5 - SYSTEM BOOT SEQUENCE[/color]\n\n[color=#66FF66]Initializing core systems...[/color]\n[color=#FFFF00]Loading BIOS... OK[/color]\n[color=#FFFF00]POST (Power-On Self Test)... OK[/color]\n[color=#FFFF00]Detecting hardware...[/color]\n[color=#00FF00]  - CPU: 4.77 MHz 8088 Compatible[/color]\n[color=#00FF00]  - RAM: 640 KB OK[/color]\n[color=#00FF00]  - CRT Display: Green Phosphor Monitor OK[/color]\n[color=#FFFF00]Loading device drivers...[/color]\n[color=#00FF00]  - Keyboard driver loaded[/color]\n[color=#00FF00]  - Timer driver loaded[/color]\n[color=#00FF00]  - Storage driver loaded[/color]"},
		{"delay": 1.5, "text": "[color=#00FF41]THE SAFE PLACE v0.9.7.5 - SYSTEM BOOT SEQUENCE[/color]\n\n[color=#66FF66]Initializing core systems...[/color]\n[color=#FFFF00]Loading BIOS... OK[/color]\n[color=#FFFF00]POST (Power-On Self Test)... OK[/color]\n[color=#FFFF00]Detecting hardware...[/color]\n[color=#00FF00]  - CPU: 4.77 MHz 8088 Compatible[/color]\n[color=#00FF00]  - RAM: 640 KB OK[/color]\n[color=#00FF00]  - CRT Display: Green Phosphor Monitor OK[/color]\n[color=#FFFF00]Loading device drivers...[/color]\n[color=#00FF00]  - Keyboard driver loaded[/color]\n[color=#00FF00]  - Timer driver loaded[/color]\n[color=#00FF00]  - Storage driver loaded[/color]\n[color=#FFFF00]Loading game data...[/color]"},
		{"delay": 0.8, "text": "[color=#00FF41]THE SAFE PLACE v0.9.7.5 - SYSTEM BOOT SEQUENCE[/color]\n\n[color=#66FF66]Initializing core systems...[/color]\n[color=#FFFF00]Loading BIOS... OK[/color]\n[color=#FFFF00]POST (Power-On Self Test)... OK[/color]\n[color=#FFFF00]Detecting hardware...[/color]\n[color=#00FF00]  - CPU: 4.77 MHz 8088 Compatible[/color]\n[color=#00FF00]  - RAM: 640 KB OK[/color]\n[color=#00FF00]  - CRT Display: Green Phosphor Monitor OK[/color]\n[color=#FFFF00]Loading device drivers...[/color]\n[color=#00FF00]  - Keyboard driver loaded[/color]\n[color=#00FF00]  - Timer driver loaded[/color]\n[color=#00FF00]  - Storage driver loaded[/color]\n[color=#FFFF00]Loading game data...[/color]\n[color=#00FF00]  - Item database: 88 items loaded[/color]"},
	{"delay": 0.6, "text": "[color=#00FF41]THE SAFE PLACE v0.9.7.5 - SYSTEM BOOT SEQUENCE[/color]\n\n[color=#66FF66]Initializing core systems...[/color]\n[color=#FFFF00]Loading BIOS... OK[/color]\n[color=#FFFF00]POST (Power-On Self Test)... OK[/color]\n[color=#FFFF00]Detecting hardware...[/color]\n[color=#00FF00]  - CPU: 4.77 MHz 8088 Compatible[/color]\n[color=#00FF00]  - RAM: 640 KB OK[/color]\n[color=#00FF00]  - CRT Display: Green Phosphor Monitor OK[/color]\n[color=#FFFF00]Loading device drivers...[/color]\n[color=#00FF00]  - Keyboard driver loaded[/color]\n[color=#00FF00]  - Timer driver loaded[/color]\n[color=#00FF00]  - Storage driver loaded[/color]\n[color=#FFFF00]Loading game data...[/color]\n[color=#00FF00]  - Item database: 88 items loaded[/color]\n[color=#00FF00]  - Event database: 78 events loaded[/color]"},
	{"delay": 0.7, "text": "[color=#00FF41]THE SAFE PLACE v0.9.7.5 - SYSTEM BOOT SEQUENCE[/color]\n\n[color=#66FF66]Initializing core systems...[/color]\n[color=#FFFF00]Loading BIOS... OK[/color]\n[color=#FFFF00]POST (Power-On Self Test)... OK[/color]\n[color=#FFFF00]Detecting hardware...[/color]\n[color=#00FF00]  - CPU: 4.77 MHz 8088 Compatible[/color]\n[color=#00FF00]  - RAM: 640 KB OK[/color]\n[color=#00FF00]  - CRT Display: Green Phosphor Monitor OK[/color]\n[color=#FFFF00]Loading device drivers...[/color]\n[color=#00FF00]  - Keyboard driver loaded[/color]\n[color=#00FF00]  - Timer driver loaded[/color]\n[color=#00FF00]  - Storage driver loaded[/color]\n[color=#FFFF00]Loading game data...[/color]\n[color=#00FF00]  - Item database: 88 items loaded[/color]\n[color=#00FF00]  - Event database: 78 events loaded[/color]\n[color=#00FF00]  - Quest system: initialized[/color]"},
	{"delay": 1.0, "text": "[color=#00FF41]THE SAFE PLACE v0.9.7.5 - SYSTEM BOOT SEQUENCE[/color]\n\n[color=#66FF66]Initializing core systems...[/color]\n[color=#FFFF00]Loading BIOS... OK[/color]\n[color=#FFFF00]POST (Power-On Self Test)... OK[/color]\n[color=#FFFF00]Detecting hardware...[/color]\n[color=#00FF00]  - CPU: 4.77 MHz 8088 Compatible[/color]\n[color=#00FF00]  - RAM: 640 KB OK[/color]\n[color=#00FF00]  - CRT Display: Green Phosphor Monitor OK[/color]\n[color=#FFFF00]Loading device drivers...[/color]\n[color=#00FF00]  - Keyboard driver loaded[/color]\n[color=#00FF00]  - Timer driver loaded[/color]\n[color=#00FF00]  - Storage driver loaded[/color]\n[color=#FFFF00]Loading game data...[/color]\n[color=#00FF00]  - Item database: 88 items loaded[/color]\n[color=#00FF00]  - Event database: 78 events loaded[/color]\n[color=#00FF00]  - Quest system: initialized[/color]\n[color=#FFFF00]Starting game engine...[/color]"},
	{"delay": 0.8, "text": "[color=#00FF41]THE SAFE PLACE v0.9.7.5 - SYSTEM BOOT SEQUENCE[/color]\n\n[color=#66FF66]Initializing core systems...[/color]\n[color=#FFFF00]Loading BIOS... OK[/color]\n[color=#FFFF00]POST (Power-On Self Test)... OK[/color]\n[color=#FFFF00]Detecting hardware...[/color]\n[color=#00FF00]  - CPU: 4.77 MHz 8088 Compatible[/color]\n[color=#00FF00]  - RAM: 640 KB OK[/color]\n[color=#00FF00]  - CRT Display: Green Phosphor Monitor OK[/color]\n[color=#FFFF00]Loading device drivers...[/color]\n[color=#00FF00]  - Keyboard driver loaded[/color]\n[color=#00FF00]  - Timer driver loaded[/color]\n[color=#00FF00]  - Storage driver loaded[/color]\n[color=#FFFF00]Loading game data...[/color]\n[color=#00FF00]  - Item database: 88 items loaded[/color]\n[color=#00FF00]  - Event database: 78 events loaded[/color]\n[color=#00FF00]  - Quest system: initialized[/color]\n[color=#FFFF00]Starting game engine...[/color]\n[color=#00FF00]  - Core systems online[/color]"},
	{"delay": 0.6, "text": "[color=#00FF41]THE SAFE PLACE v0.9.7.5 - SYSTEM BOOT SEQUENCE[/color]\n\n[color=#66FF66]Initializing core systems...[/color]\n[color=#FFFF00]Loading BIOS... OK[/color]\n[color=#FFFF00]POST (Power-On Self Test)... OK[/color]\n[color=#FFFF00]Detecting hardware...[/color]\n[color=#00FF00]  - CPU: 4.77 MHz 8088 Compatible[/color]\n[color=#00FF00]  - RAM: 640 KB OK[/color]\n[color=#00FF00]  - CRT Display: Green Phosphor Monitor OK[/color]\n[color=#FFFF00]Loading device drivers...[/color]\n[color=#00FF00]  - Keyboard driver loaded[/color]\n[color=#00FF00]  - Timer driver loaded[/color]\n[color=#00FF00]  - Storage driver loaded[/color]\n[color=#FFFF00]Loading game data...[/color]\n[color=#00FF00]  - Item database: 88 items loaded[/color]\n[color=#00FF00]  - Event database: 78 events loaded[/color]\n[color=#00FF00]  - Quest system: initialized[/color]\n[color=#FFFF00]Starting game engine...[/color]\n[color=#00FF00]  - Core systems online[/color]\n[color=#00FF00]  - UI systems initialized[/color]"},
	{"delay": 1.2, "text": "[color=#00FF41]THE SAFE PLACE v0.9.7.5 - SYSTEM BOOT SEQUENCE[/color]\n\n[color=#66FF66]Initializing core systems...[/color]\n[color=#FFFF00]Loading BIOS... OK[/color]\n[color=#FFFF00]POST (Power-On Self Test)... OK[/color]\n[color=#FFFF00]Detecting hardware...[/color]\n[color=#00FF00]  - CPU: 4.77 MHz 8088 Compatible[/color]\n[color=#00FF00]  - RAM: 640 KB OK[/color]\n[color=#00FF00]  - CRT Display: Green Phosphor Monitor OK[/color]\n[color=#FFFF00]Loading device drivers...[/color]\n[color=#00FF00]  - Keyboard driver loaded[/color]\n[color=#00FF00]  - Timer driver loaded[/color]\n[color=#00FF00]  - Storage driver loaded[/color]\n[color=#FFFF00]Loading game data...[/color]\n[color=#00FF00]  - Item database: 88 items loaded[/color]\n[color=#00FF00]  - Event database: 78 events loaded[/color]\n[color=#00FF00]  - Quest system: initialized[/color]\n[color=#FFFF00]Starting game engine...[/color]\n[color=#00FF00]  - Core systems online[/color]\n[color=#00FF00]  - UI systems initialized[/color]\n[color=#00FF00]  - Game ready![/color]"},
	{"delay": 1.5, "text": "[color=#00FF41]THE SAFE PLACE v0.9.7.5 - SYSTEM BOOT SEQUENCE[/color]\n\n[color=#66FF66]Initializing core systems...[/color]\n[color=#FFFF00]Loading BIOS... OK[/color]\n[color=#FFFF00]POST (Power-On Self Test)... OK[/color]\n[color=#FFFF00]Detecting hardware...[/color]\n[color=#00FF00]  - CPU: 4.77 MHz 8088 Compatible[/color]\n[color=#00FF00]  - RAM: 640 KB OK[/color]\n[color=#00FF00]  - CRT Display: Green Phosphor Monitor OK[/color]\n[color=#FFFF00]Loading device drivers...[/color]\n[color=#00FF00]  - Keyboard driver loaded[/color]\n[color=#00FF00]  - Timer driver loaded[/color]\n[color=#00FF00]  - Storage driver loaded[/color]\n[color=#FFFF00]Loading game data...[/color]\n[color=#00FF00]  - Item database: 88 items loaded[/color]\n[color=#00FF00]  - Event database: 78 events loaded[/color]\n[color=#00FF00]  - Quest system: initialized[/color]\n[color=#FFFF00]Starting game engine...[/color]\n[color=#00FF00]  - Core systems online[/color]\n[color=#00FF00]  - UI systems initialized[/color]\n[color=#00FF00]  - Game ready![/color]\n\n[color=#FFFFFF]Press any key to continue...[/color]"}
]

var step_timer: float = 0.0
var waiting_for_input: bool = false

func _ready():
	# Assicurati che il CRT sia attivo e completo (power-on già fatto)
	if crt_display and crt_display.material:
		crt_display.visible = true
		var crt_material = crt_display.material as ShaderMaterial
		if crt_material:
			# CRT già acceso dalla scena precedente
			crt_material.set_shader_parameter("power_on_time", 10.0)

	print("🎮 BootSequence: Avvio simulazione boot sistema operativo")

func _process(delta: float):
	if waiting_for_input:
		return

	step_timer += delta

	if current_step < BOOT_SEQUENCE.size():
		var current_boot_step = BOOT_SEQUENCE[current_step]
		if step_timer >= current_boot_step.delay:
			boot_text.text = current_boot_step.text
			current_step += 1
			step_timer = 0.0
	else:
		# Boot completato, aspetta input per continuare
		waiting_for_input = true

func _input(event):
	if waiting_for_input and event is InputEventKey and event.pressed:
		# Boot completato, vai al main menu
		print("🎮 BootSequence: Boot completato - Accesso al sistema")
		get_tree().change_scene_to_file("res://scenes/MainMenu.tscn")
